version: '3'

services:
  quanlyduan:
    container_name: quanlyduan
    image: sanhphanvan/quanlyduan:v0.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8888:3000
    command: ["rails", "server"]
